<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>todo</string>
	</array>
	<key>name</key>
	<string>TODO</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>(^\s*\[ \])</string>
			<key>name</key>
			<string>text.todo</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(^\s*\[o\])</string>
			<key>name</key>
			<string>keyword.blocked.todo</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(^\s*\[\.\])</string>
			<key>name</key>
			<string>string.constant.todo</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(^\s*\[x\])</string>
			<key>name</key>
			<string>entity.name.function.todo</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^\s*\[-\].*</string>
			<key>name</key>
			<string>comment.message.todo</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(^\s*\[~\])</string>
			<key>name</key>
			<string>support.function.todo</string>
		</dict>
		<dict>
			<key>match</key>
			<string>.*(?=(\((cl|personal)\)|\[(cl|personal)\]))</string>
			<key>name</key>
			<string>comment.message.todo</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(\(cl\)|\[cl\])</string>
			<key>name</key>
			<string>support.function.todo</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(\((\w|[-])+\)|\[(\w|[-])+\])</string>
			<key>name</key>
			<string>string</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>^---</string>
			<key>end</key>
			<string>$</string>
			<key>name</key>
			<string>comment.header.todo</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>-</string>
					<key>name</key>
					<string>comment.block.header.todo</string>
					<key>patterns</key>
					<array>
					</array>
				</dict>
				<dict>
					<key>match</key>
					<string>[0-9]</string>
					<key>name</key>
					<string>numeric.constant.date.todo</string>
					<key>patterns</key>
					<array>
					</array>
				</dict>
			</array>
		</dict>
	</array>
	<key>repository</key>
	<dict>
	</dict>
	<key>scopeName</key>
	<string>source.todolist</string>
	<key>uuid</key>
	<string>07629b98-022c-4204-a227-aa65ae352fab</string>
</dict>
</plist>
