<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>todo</string>
	</array>
	<key>name</key>
	<string>To Do lists</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>(^\s*\[ \])</string>
			<key>name</key>
			<string>text</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(^\s*\[o\])</string>
			<key>name</key>
			<string>keyword</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?&lt;=\[o\]) \(.*\)</string>
			<key>name</key>
			<string>keyword</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(^\s*\[\.\])</string>
			<key>name</key>
			<string>string</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(^\s*\[x\])</string>
			<key>name</key>
			<string>entity.name.function</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^\s*\[-\].*</string>
			<key>name</key>
			<string>comment</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(^\s*\[~\])</string>
			<key>name</key>
			<string>storage.type</string>
		</dict>
		<dict>
			<key>match</key>
			<string>.*(?=(\((cl|personal)\)|\[(cl|personal)\]))</string>
			<key>name</key>
			<string>comment.message.todo</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(\(personal\)|\[personal\])</string>
			<key>name</key>
			<string>comment.message.todo</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\[Dev\]</string>
			<key>name</key>
			<string>support.function</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\[Landing\]</string>
			<key>name</key>
			<string>variable.function</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(\(cl\)|\[cl\])</string>
			<key>name</key>
			<string>storage.type</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(\((\w|[-])+\)|\[(\w|[-])+\])</string>
			<key>name</key>
			<string>string</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>^---</string>
			<key>end</key>
			<string>$</string>
			<key>name</key>
			<string>comment</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>-</string>
					<key>name</key>
					<string>comment</string>
					<key>patterns</key>
					<array/>
				</dict>
				<dict>
					<key>match</key>
					<string>[0-9]{4}/[0-9]{2}/[0-9]{2}</string>
					<key>name</key>
					<string>constant.numeric</string>
					<key>patterns</key>
					<array/>
				</dict>
				<dict>
					<key>match</key>
					<string>.</string>
					<key>name</key>
					<string>support.function</string>
					<key>patterns</key>
					<array/>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>^Web.*\(\w+(/\w+)?\)$</string>
			<key>end</key>
			<string>(?=^---)</string>
			<key>name</key>
			<string>comment</string>
			<key>patterns</key>
			<array/>
		</dict>
		<dict>
			<key>begin</key>
			<string>^```php</string>
			<key>end</key>
			<string>^```</string>
			<key>name</key>
			<string>php</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\$\w+</string>
					<key>name</key>
					<string>storage.types</string>
				</dict>
				<dict>
					<key>include</key>
					<string>source.php</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>^```(sh|bash)</string>
			<key>end</key>
			<string>^```</string>
			<key>name</key>
			<string>bash</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.shell</string>
				</dict>
			</array>
		</dict>
	</array>
	<key>repository</key>
	<dict/>
	<key>scopeName</key>
	<string>source.todolist</string>
	<key>uuid</key>
	<string>3bca375a-ac87-4b15-88ea-eb6cc05de48e</string>
</dict>
</plist>
